### ISSUE TITLE
Replacing the icons in the Trace module

### ISSUE THREAD

**Issue by lidida** [lidida/intrace#3]
Need to replace 3 icons with the new ones that are attached:

1) Materials

![fabric](https://user-images.githubusercontent.com/45885845/60262089-4a172e80-98d5-11e9-9a7d-1339f7692ec4.png)

2) Waste

![recycle-sign](https://user-images.githubusercontent.com/45885845/60262095-4d121f00-98d5-11e9-9b75-f1407cd1c13c.png)

3) Wear

![costume-clothes](https://user-images.githubusercontent.com/45885845/60262101-4f747900-98d5-11e9-90af-a131a756ab12.png)

OR 

![tshirt](https://user-images.githubusercontent.com/45885845/60262106-526f6980-98d5-11e9-9d6c-d26e0d0be3ea.png)

**Comment by cyri113** [comment]
Not the right app
